config/routes.rb
Gardino::Application.routes.draw do
  

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :relays do
  collection {
      post 'turnoff'
      post 'turnon'
  }
  end
  resources :sensors do
    collection {
      post 'sensorread'
    }
  end
  get "welcome/index"

  root 'welcome#index'

  

end

app/models/relay.rb
class Relay < ActiveRecord::Base
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/relays_controller.rb
class RelaysController < ApplicationController
  before_action :set_relay, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token
  # GET /relays
  # GET /relays.json
  def index
    @relays = Relay.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /relays/1
  # GET /relays/1.json
  def show
  end

  # GET /relays/new
  def new
    @relay = Relay.new
  end

  # GET /relays/1/edit
  def edit
  end

  # POST /relays
  # POST /relays.json
  def create
    @relay = Relay.new(relay_params)
    @rnum = @relay.number
    @rpin = @relay.pin
    eval("$relay#{@rnum} = Dino::Components::Led.new(pin: @rpin, board: Gardino::Application.config.board)")
    respond_to do |format|
      if @relay.save
        format.html { redirect_to @relay, notice: 'Relay was successfully created.' }
        format.json { render action: 'show', status: :created, location: @relay }
      else
        format.html { render action: 'new' }
        format.json { render json: @relay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relays/1
  # PATCH/PUT /relays/1.json
  def update
    respond_to do |format|
      if @relay.update(relay_params)
        format.html { redirect_to @relay, notice: 'Relay was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @relay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relays/1
  # DELETE /relays/1.json
  def destroy
    @relay.destroy
    respond_to do |format|
      format.html { redirect_to relays_url }
      format.json { head :no_content }
    end
  end

  # POST /relays
  # POST /relays.json
  def turnoff
    @relay = Relay.find(params[:id])
    @relayn = @relay.number
    @relayh = eval("$relay#{@relayn}")
    @relayh.off
    @relay.status="off"
    @relay.save
    @relays = Relay.all
    respond_to do |format|
      format.js
    end
  end

  # POST /relays
  # POST /relays.json
  def turnon
    @relay = Relay.find(params[:id])
    @relayn = @relay.number
    @relayh = eval("$relay#{@relayn}")
    @relayh.on
    @relay.status="on"
    @relay.save
    @relays = Relay.all
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relay
      @relay = Relay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relay_params
      params.require(:relay).permit(:name, :pin, :number, :status)
    end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy, :read]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)
    @snum = @sensor.number
    @spin = @sensor.pin
    @stype = @sensor.sensor_type
    if @stype == "DHT"
      eval("$sensor#{@snum}temp = Dino::Components::DHT::Temperature.new(pin: @spin, board: Gardino::Application.config.board)")
      eval("$sensor#{@snum}humidity = Dino::Components::DHT::Humidity.new(pin: @spin, board: Gardino::Application.config.board)")
    end
    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sensor }
      else
        format.html { render action: 'new' }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url }
      format.json { head :no_content }
    end
  end

  # POST /sensors
  # POST /sensors.json
  def sensorread
    @sensor = Sensor.find(params[:id])
    @snum = @sensor.number
    @stype = @sensor.sensor_type
    if @stype == "DHT"
            
      eval("$sensor#{@snum}temp").read do |temperature|
        @stempread = "#{temperature}"
      end
      sleep 2
      eval("$sensor#{@snum}humidity").read do |humidity|
         @shumidityread = "#{humidity}"
      end
      @sensor.last_reading = "Temp:#{@stempread}C Humidity:#{@shumidityread}%"
      @sensor.save
    end
    @sensors = Sensor.all
    respond_to do |format|
      format.js
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:name, :sensor_type, :pin, :number, :last_reading, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relays_helper.rb
module RelaysHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Gardino", root_path, :class => 'brand' %>
<ul class="nav">
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gardino</title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Bootstrap Devise Cancan" %>">
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>    
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
<!-- Wrap all page content here -->


      <!-- Fixed navbar -->
<!--       <div class="navbar navbar-fixed-top">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Gardino</a>
          <div class="nav-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/relays">Relays</a></li>
              <li><a href="/sensors">Sensors</a></li>
              <li><a href="/schedules">Schedules</a></li>
              
            </ul>
          </div>
        </div>
      </div> -->

      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Gardino</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/relays">Relays</a></li>
            <li><a href="/sensors">Sensors</a></li>
            <li><a href="/schedules">Schedules</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
        </div>
      </nav>


      <!-- Begin page content -->
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
    <div id="footer">
      <div class="container">
        <p class="text-muted credit"><a href="https://github.com/justinledwards/gardino">Github Gardino Project</a></p>
      </div>
    </div>

    
  </body>
</html>

app/views/relays/_form.html.erb
<%= form_for(@relay) do |f| %>
  <% if @relay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relay.errors.count, "error") %> prohibited this relay from being saved:</h2>

      <ul>
      <% @relay.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pin %><br>
    <%= f.number_field :pin %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>

    <%= f.hidden_field :status, :value => "off" %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relays/_relay.html.erb
<p class="lead">Relays</p>
<div class="row">
<div class="col-xs-6 col-sm-6 col-md-6">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Action</th>
      <th>Name</th>
<!--       <th>Pin</th>
      <th>Number</th> -->
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @relays.each do |relay| %>
      <tr>
        <td><% if relay.status == "off" %>
	<button onClick="turnon('<%= relay.id %>')" class="btn btn-danger btn-small"> Turn on </button>
        <% elsif relay.status == "on" %>
        <button onClick="turnoff('<%= relay.id %>')" class="btn btn-success btn-small"> Turn off </button>
        <% end %>
	</td>
        <td><%= relay.name %></td>
<!--         <td><%= relay.pin %></td>
        <td><%= relay.number %></td> -->
	<td><%= relay.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>

<%= link_to 'New Relay', new_relay_path, :class => "btn btn-mini btn-primary" %>
<p>&nbsp;</p>


<script>

function turnoff(number)
{
  $.ajax({
    url: "/relays/turnoff",
    type: "POST",
    data: {id: number},
    dataType: "script",
    success: function(resp){
      //alert( "Turned off: " + number );
     }
  });
}

function turnon(number)
{
  $.ajax({
    url: "/relays/turnon",
    type: "POST",
    data: {id: number},
    dataType: "script",
    success: function(resp){
      //alert( "Turned on: " + number );
     }
  });
}

</script>

app/views/relays/edit.html.erb
<h1>Editing relay</h1>

<%= render 'form' %>

<%= link_to 'Show', @relay %> |
<%= link_to 'Back', relays_path %>

app/views/relays/index.html.erb
<div class="span12" id="relays">
<%= render :partial => "relay", :object => @relays %>
</div>

app/views/relays/index.js.erb
$('#relays').html('<%= escape_javascript render(:partial => "relay", :object => @relays) %>');

app/views/relays/new.html.erb
<h1>New relay</h1>

<%= render 'form' %>

<%= link_to 'Back', relays_path %>

app/views/relays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @relay.name %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @relay.pin %>
</p>

<p>
  <strong>Number:</strong>
  <%= @relay.number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @relay.status %>
</p>

<%= link_to 'Edit', edit_relay_path(@relay) %> |
<%= link_to 'Back', relays_path %>

app/views/relays/turnoff.js.erb
$('#relays').html('<%= escape_javascript render(:partial => "relay", :object => @relays) %>');

app/views/relays/turnon.js.erb
$('#relays').html('<%= escape_javascript render(:partial => "relay", :object => @relays) %>');

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sensor_type %><br>
    <%= f.text_field :sensor_type %>
  </div>
  <div class="field">
    <%= f.label :pin %><br>
    <%= f.number_field :pin %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :last_reading %><br>
    <%= f.text_field :last_reading %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensors/_sensor.html.erb
<p class="lead">Sensors</p>
<div class="row">
<div class="col-xs-6 col-sm-6 col-md-6">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Action</th>
      <th>Name</th>
      <th>Type</th>
      <!-- <th>Pin</th> -->
      <!-- <th>Number</th> -->
      <th>Last reading</th>
      <!-- <th>Description</th> -->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><button onClick="sensorread('<%= sensor.id %>')" class="btn btn-info btn-small"> Read </button></td>
        <td><%= sensor.name %></td>
        <td><%= sensor.sensor_type %></td>
        <!-- <td><%= sensor.pin %></td> -->
        <!-- <td><%= sensor.number %></td> -->
        <td><%= sensor.last_reading %></td>
        <!-- <td><%= sensor.description %></td> -->
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>

<%= link_to 'New Sensor', new_sensor_path, :class => "btn btn-mini btn-primary" %>

<p>&nbsp;</p>

<script>

function sensorread(number)
{
  $.ajax({
    url: "/sensors/sensorread",
    type: "POST",
    data: {id: number},
    dataType: "script",
    success: function(resp){
      //alert( "Read: " + number );
     }
  });
}
</script>

app/views/sensors/edit.html.erb
<h1>Editing sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<div class="span12" id="sensors">
<%= render :partial => "sensor", :object => @sensors %>
</div>

app/views/sensors/new.html.erb
<h1>New sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/sensorread.js.erb
$('#sensors').html('<%= escape_javascript render(:partial => "sensor", :object => @sensors) %>');

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sensor.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @sensor.sensor_type %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @sensor.pin %>
</p>

<p>
  <strong>Number:</strong>
  <%= @sensor.number %>
</p>

<p>
  <strong>Last reading:</strong>
  <%= @sensor.last_reading %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sensor.description %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Gardino</h1>
<%# $sensor1.read { |value|  $temperature = (((value.to_f * 0.004882814) - 0.5) * 100) * (9.0/5.0) + 32.00  } 
%>
<p>Temperature is <%=# $temperature.round(1) 
%>F
</p>